In [22]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ここでやりたいことはある都市がoverlapで残った都市が消された都市のどれと被っているかを確かめる
# 方法 
# 1860都市を都市番号のintegerで白地図に順番に追加する
# 追加するときに0以外の番号がすでに含まれいる場合
# そのグリッド座標の集合 + 含まれている都市番号 + 追加しようとした都市番号を保存する

In [23]:
# vld_cty_にはNoMASKのcity_maskが存在しない
# 除去するprocessを加える必要がある

workdir = f'/mnt/c/Users/tsimk/Downloads/dotfiles/h08/global_city/dat/vld_cty_'
savedir = f'/mnt/c/Users/tsimk/Downloads/dotfiles/h08/camacity/dat/ovlpcomb'

canvas = np.zeros((2160, 4320))

for cty_ind in range(1, 1861):
    file_path = f'{workdir}/city_{cty_ind:08}.gl5'
    if not os.path.exists(file_path):
        print(f"{cty_ind} is NoMASK")
        continue
        
    mask = np.fromfile(file_path, dtype='float32').reshape(2160, 4320)
        
    # maskが0でない場所のインデックスを取得(tuple形式)
    non_zero_coords = np.where(mask != 0)
    
    # キャンバスのmask位置に存在する値を取得
    settled_values = canvas[non_zero_coords]

    # ユニークな値は?
    unq = np.unique(settled_values)
    unq_non_zero = unq[unq > 0]
    
    if np.sum(settled_values) > 0:
        print(f'cty_ind:{cty_ind} is overlapped with cty_ind:{unq_non_zero}')

        overlap_ind = np.where(canvas[non_zero_coords] != 0)
        overlap_y = non_zero_coords[0][overlap_ind]
        overlap_x = non_zero_coords[1][overlap_ind]
        print(overlap_y, overlap_x)
        
        df = pd.DataFrame({'y_coord': overlap_y, 'x_coord': overlap_x})
        df.to_csv(f'{savedir}/{cty_ind:08}_{unq_non_zero[0]:08}.csv', index=False)

    else:
        # update canvas
        canvas[non_zero_coords] = cty_ind

cty_ind:42 is overlapped with cty_ind:[24.]
[807] [3526]
cty_ind:43 is overlapped with cty_ind:[24.]
[809 809] [3528 3529]
cty_ind:44 is overlapped with cty_ind:[23.]
[801 802 802 802 803 803] [3519 3518 3519 3520 3517 3518]
cty_ind:122 is overlapped with cty_ind:[77.]
[1394 1394 1394 1395] [2494 2495 2496 2494]
cty_ind:148 is overlapped with cty_ind:[23.]
[805] [3519]
152 is NoMASK
cty_ind:158 is overlapped with cty_ind:[26.]
[629 629 629] [3681 3682 3683]
cty_ind:160 is overlapped with cty_ind:[144.]
[699 700 700 700] [3601 3601 3602 3603]
168 is NoMASK
174 is NoMASK
cty_ind:206 is overlapped with cty_ind:[84.]
[779] [3617]
225 is NoMASK
cty_ind:227 is overlapped with cty_ind:[207.]
[946 947 948 948] [3071 3071 3071 3072]
cty_ind:236 is overlapped with cty_ind:[128.]
[687 688 689 689 689 690 690 690] [755 755 755 756 757 755 756 757]
237 is NoMASK
cty_ind:252 is overlapped with cty_ind:[52.]
[718 718] [3603 3604]
cty_ind:268 is overlapped with cty_ind:[207.]
[946 946 947 948 948] [30